CREATE TABLE IF NOT EXISTS  `deals` (
 id int(40) NOT NULL auto_increment,
 business_name VARCHAR(128) NOT NULL,
 title VARCHAR(128) NOT NULL,
 description TEXT NOT NULL,
 address_1 VARCHAR(128) NOT NULL,
 address_2 VARCHAR(128) NOT NULL,
 city VARCHAR(128) NOT NULL,
 state VARCHAR(3) NOT NULL,
 zip_code VARCHAR(10) NOT NULL,
 phone VARCHAR(20) NOT NULL,
 email VARCHAR(128) NOT NULL,
 PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;